name: Build and Push DahCore Image

on:
  schedule:
    - cron: '0 3 * * 0' # Every Sunday at 03:00 UTC
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  IMAGE_NAME: dahcore
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Registry
        if: github.event_name != 'pull_request'
        uses: redhat-actions/podman-login@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image with Buildah
        id: build-image
        uses: redhat-actions/buildah-build@v3
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: latest ${{ github.ref_name }}
          containerfiles: |
            ./Containerfile

      - name: Lowercase Registry Owner
        id: registry_meta
        run: |
          echo "owner=${OWNER,,}" >> $GITHUB_OUTPUT
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: Push to Registry
        id: push-to-registry
        if: github.event_name != 'pull_request'
        uses: redhat-actions/push-to-registry@v3
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.REGISTRY }}/${{ steps.registry_meta.outputs.owner }}

      - name: Install Cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v4.1.0

      - name: Sign DahCore Image
        if: github.event_name != 'pull_request'
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          cosign sign --yes --tlog-upload=false --key env://COSIGN_PRIVATE_KEY \
            --registry-username "${{ github.actor }}" \
            --registry-password "${{ secrets.GITHUB_TOKEN }}" \
            "${{ env.REGISTRY }}/${{ steps.registry_meta.outputs.owner }}/${{ env.IMAGE_NAME }}@${{ steps.push-to-registry.outputs.digest }}"
